# Generated by Django 3.2.3 on 2021-07-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('age', models.IntegerField(default=0, null=True)),
                ('state', models.CharField(max_length=30, null=True)),
                ('country', models.CharField(choices=[('us', 'USA'), ('vn', 'Viet Nam')], max_length=5, null=True)),
                ('ts', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
