# Generated by Django 3.2.3 on 2021-07-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210712_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('vn', 'Vietnamese')], default='en', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
