# Generated by Django 3.2.3 on 2021-07-14 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20210713_0850'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Therapist',
        ),
    ]
