# Generated by Django 3.2.3 on 2021-07-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210624_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='langauge',
            field=models.CharField(choices=[('en', 'English'), ('vn', 'Vietnamese')], default='en', max_length=5),
        ),
    ]
