# Generated by Django 3.2.3 on 2021-07-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_langauge'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_subscribed_newsletters',
            field=models.BooleanField(default=False),
        ),
    ]
