# Generated by Django 3.2.3 on 2021-07-02 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='langauge',
            new_name='language',
        ),
    ]
