# Generated by Django 3.2.3 on 2021-07-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210712_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_subscribe',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
