# Generated by Django 3.2.3 on 2021-07-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_is_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('vn', 'Vietnamese')], default='en', max_length=3),
        ),
    ]
