# Generated by Django 3.2.3 on 2021-06-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegasus_examples', '0003_auto_20191004_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
